# Generated by Django 4.1.3 on 2023-06-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
