# Generated by Django 4.1.3 on 2023-06-25 17:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('image', models.ImageField(upload_to='images/')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('brand', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('size', models.CharField(default='', max_length=50)),
                ('category', models.ForeignKey(db_column='type2', on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
